export const products = [
  { id: 1, name: "Smart Tv", price: "200$", count: 0 },
  { id: 2, name: "Smart Tv", price: "200$", count: 0 },
  { id: 3, name: "Smart Tv", price: "200$", count: 0 },
  { id: 4, name: "Smart Tv", price: "200$", count: 0 },
  { id: 5, name: "Smart Tv", price: "200$", count: 0 },
  { id: 6, name: "Smart Tv", price: "200$", count: 0 },
  { id: 7, name: "Smart Tv", price: "200$", count: 0 },
  { id: 8, name: "Smart Tv", price: "200$", count: 0 },
  { id: 9, name: "Smart Tv", price: "200$", count: 0 },
  { id: 10, name: "Smart Tv", price: "200$", count: 0 },
  { id: 11, name: "Smart Tv", price: "200$", count: 0 },
  { id: 12, name: "Smart Tv", price: "200$", count: 0 },
  { id: 13, name: "Smart Tv", price: "200$", count: 0 },
  { id: 14, name: "Smart Tv", price: "200$", count: 0 },
  { id: 15, name: "Smart Tv", price: "200$", count: 0 },
  { id: 16, name: "Smart Tv", price: "200$", count: 0 },
];
